rest-climalert.base-url=http://api.weatherapi.com/v1/current.json
rest-climalert.api-key=d51fbc811653455f864193752260207
rest-climalert.location=Argentina

notificaciones.proveedor=sendgrid

sendgrid.api-key=${SENDGRID_API_KEY}
sendgrid.from-email=tvallejos@frba.utn.edu.ar